[workspace]
members = ["src/evedb-core", "src/evedb-cli"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.98"
license = "AGPL-3.0-only"
repository = "https://github.com/Rea1Blank/EveDB"
publish = false

[workspace.dependencies]
evedb-core = { path = "src/evedb-core" }

[workspace.lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"

[workspace.lints.clippy]
all = "warn"

[profile.release]
lto = "thin"
codegen-units = 1
